### PR TITLE
Imperative semantics

### PR DESCRIPTION
**Pull request by Aqissiaq**
Non-Ott imperative semantics and typing relation.
Still missing class and method typing, as well as a Countable instance for tasks.

### CODE REVIEW

**Comment by palmskog** [comment]
@Aqissiaq it looks like this builds on top of the changes in #18, can you confirm?

I'm thinking it could be a good idea try to fix up #18, merge it to `master`, and then rebase this PR? The diff would probably be a lot cleaner.

**Comment by Aqissiaq** [comment]
Yes, this builds on #18. I will have a look at that either tonight or tomorrow

**Comment by palmskog** [comment]
I plan to take a look at #18, but then let's aim to get that PR merged before I do a larger review of this one. In particular, I think a lot of the equality decision procedures are not necessary.

**Comment by palmskog** [comment]
@Aqissiaq would be great if this could be rebased on top of new `master`, so the diff is easier to review.

**Comment by Aqissiaq** [comment]
I thought I did it right, but it still looks a bit messy. The diff for the last commit looks much nicer, at least.

**Comment by palmskog** [comment]
@Aqissiaq ah, I think I see now what the problem is, there is a lot of diverging history. I think what may be easiest is to "re-add" the imperative changes on top of current `master`, let me do a quick attempt at this.

**Comment by palmskog** [comment]
Closing since superceded by #22

**Pull request closed without merging**
